<?php
/**
 * Run this once after importing database.sql to refresh demo password hashes
 * with hashes generated by YOUR server's PHP build.
 * Delete this file afterwards.
 */
require_once __DIR__ . '/config/database.php';

$accounts = [
    'admin'  => ['password' => 'admin123',  'role' => 'admin'],
    'editor' => ['password' => 'editor123', 'role' => 'editor'],
];

foreach ($accounts as $username => $info) {
    $hash = password_hash($info['password'], PASSWORD_DEFAULT);
    $stmt = $pdo->prepare('UPDATE users SET password = ? WHERE username = ?');
    $stmt->execute([$hash, $username]);
    echo "Updated password hash for: $username\n";
}

echo "\nDone. Delete seed.php now for security.\n";
